sudo: false
language: node_js
node_js:
- iojs
before_script:
- git config --global user.email "iamstarkov+tachikombie@gmail.com"
- git config --global user.name "Tachikoma Zombie"
- git remote rm origin
- git remote add origin https://tachikombie:${GH_TOKEN}@github.com/iamstarkov/rubyunderhood.git
after_script:
- npm run f5
- npm run save
- npm run deploy
env:
  global:
    secure: OJ0p+1cq0It095Wqnq/5y59KqYvQyJyaP6ig8fVi6JVzzs2CUcIcHegYWWMqFTOnm2CHVtSQlRHg9NmAr5ewGafIMDi5Wx0oKBOkQO3mWM4gHMrLEFYTqRc0Uro0iTUiPd0ODj0drc2b/Jq3o256ASQYsUamBaPzMf7kyf1aPxqycxPiwR0O+IoxZdEp/izs4n/CGwLPZQUJk95Xn+sCLgupBcb+wdF5346hOjbGP/LXhsZPEk5c9JMb69QLvA0crBhnoxjyWo7SmbtyWJ+1SGmEOVn5rTbzrUlw3nc3LViNiHUNRtoSNDkrFx30cM/G6Cq2xmEStTwDnO0bLXpfDh0K2ScEDCScIjab3yCerTPVlbeTTjOLCEO/aRRNxfkyjligu7AK+vKZVwSuuKO9lbqX4fy/t91epNzOoyGBWp+YtyST5ldoPu4c+dB/p3jU1XcniRCkCIa0q8Ozsj3mNEouNfAAEkUyrWuAL4yhB6L8kWm1FegCUXRgj3BMK2QHlwxPRn/7UCeQTQppM+LxNkRams4ivOAdizb4iV4o1udPCNtAWcVS/ZTsw7AirwEf7dERWvK/5EjjVEjgjj85BNi+AlqX5D00qtk4tRbxeMoIX7Kn2acvpJmQDQlo5o7iBUF/3P6+YHYAViSu3zrgY0y8Kz9WUW2P24SO57bTfBw=
